version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: mkdir /tmp/results/
      - run: sudo pip install -r requirements.test.txt
      - run: tox
      - store_artifacts:
          path: /tmp/results/
