version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install ruby ruby-dev rubygems build-essential
      - run: sudo gem install --no-ri --no-rdoc fpm
      - run: mkdir /tmp/artifacts/
      - run: sudo pip install -r requirements.test.txt
      - run: tox
      - run: fpm --verbose --python-bin /usr/bin/python3.6 --python-install-data / -s python -t deb ./
      - store_artifacts:
          path: /tmp/artifacts/
