version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install ruby ruby-dev rubygems build-essential
      - run: sudo apt-get install python3-pip
      - run: sudo gem install --no-ri --no-rdoc fpm
      - run: mkdir /tmp/artifacts/
      - run: sudo pip install -r requirements.test.txt
      - run: tox
      - run: fpm --verbose --python-bin /usr/bin/python3 --python-install-data / --python-package-name-prefix python3 -d python3-yaml --python-disable-dependency pyyaml -p /tmp/artifacts/ -s python -t deb ./
      - store_artifacts:
          path: /tmp/artifacts/
